name = "djlarian-react"
account_id = "8183c3c4f59a7b1747827300bdb46c9d"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

# Configuration pour Cloudflare Pages
pages_build_output_dir = ".open-next/cloudflare"
